<template>
  <KasubagLayout>
    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-bold text-slate-950">Pengaduan Masuk</h2><p class="mt-1 text-xs text-slate-500">Hanya pengaduan yang ditugaskan ke unit Anda.</p></div><button class="rounded-full bg-slate-100 px-4 py-2 text-xs font-semibold text-slate-700" @click="load">Muat ulang</button></div><div class="mt-5 grid gap-3 md:grid-cols-3"><input v-model="query" type="search" placeholder="Cari tiket atau judul" class="rounded-xl border border-slate-200 px-4 py-2.5 text-xs" /><select v-model="status" class="rounded-xl border border-slate-200 px-4 py-2.5 text-xs"><option value="">Semua Status</option><option v-for="item in statuses" :key="item" :value="item">{{ item }}</option></select><select v-model="urgency" class="rounded-xl border border-slate-200 px-4 py-2.5 text-xs"><option value="">Semua Urgensi</option><option>Tinggi</option><option>Sedang</option><option>Rendah</option></select></div><div v-if="error" class="mt-5 rounded-lg border border-red-200 bg-red-50 p-4 text-xs text-red-700">{{ error }}</div><div class="mt-5 overflow-x-auto rounded-lg border border-slate-200"><table class="min-w-full text-left text-xs"><thead class="bg-slate-50 text-slate-500"><tr><th class="px-4 py-3">Nomor Tiket</th><th class="px-4 py-3">Judul Aduan</th><th class="px-4 py-3">Nama Mahasiswa</th><th class="px-4 py-3">Kategori</th><th class="px-4 py-3">Urgensi</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-200"><tr v-if="loading"><td colspan="7" class="px-4 py-8 text-center text-slate-500">Memuat pengaduan...</td></tr><tr v-else-if="!filtered.length"><td colspan="7" class="px-4 py-8 text-center text-slate-500">Belum ada pengaduan yang ditugaskan ke unit ini.</td></tr><tr v-for="item in filtered" v-else :key="item.id"><td class="px-4 py-3 font-semibold text-slate-950">{{ ticket(item) }}</td><td class="min-w-48 px-4 py-3">{{ item.judul }}</td><td class="px-4 py-3">{{ item.user?.nama_lengkap || '-' }}</td><td class="px-4 py-3">{{ item.kategori?.nama || '-' }}</td><td class="px-4 py-3"><StatusBadge kind="urgency" :label="item.urgensi" /></td><td class="px-4 py-3"><StatusBadge :label="item.status" /></td><td class="px-4 py-3"><router-link :to="{ name: 'KasubagDetail', params: { id: item.id } }" class="font-semibold text-blue-950 hover:underline">Detail</router-link></td></tr></tbody></table></div></section>
  </KasubagLayout>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import KasubagLayout from '../../layouts/KasubagLayout.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import service from '../../services/kasubag.service'
import { errorMessage, responseList } from '../../utils/api'
const items = ref([]); const loading = ref(true); const error = ref(''); const query = ref(''); const status = ref(''); const urgency = ref(''); const statuses = ['Diteruskan ke Unit', 'Diproses', 'Selesai', 'Menunggu Verifikasi']
const filtered = computed(() => items.value.filter((item) => { const text = `${item.kode_tiket || ''} ${item.judul || ''} ${item.user?.nama_lengkap || ''}`.toLowerCase(); return text.includes(query.value.toLowerCase()) && (!status.value || item.status === status.value) && (!urgency.value || item.urgensi === urgency.value) }))
function ticket(item) { return item.kode_tiket || `ADU-${item.id}` }
async function load() { loading.value = true; error.value = ''; try { items.value = responseList(await service.getAllPengaduan()) } catch (err) { error.value = errorMessage(err, 'Daftar pengaduan tidak dapat dimuat.') } finally { loading.value = false } }
onMounted(load)
</script>
