<template>
  <PimpinanLayout>
    <section class="space-y-5">
      <div><p class="text-[11px] font-semibold uppercase tracking-wider text-blue-950">Pimpinan Fakultas</p><h2 class="mt-1 text-xl font-bold text-slate-950">Riwayat Pengaduan Tinggi</h2><p class="mt-1 text-xs text-slate-500">Seluruh pengaduan urgensi tinggi yang pernah masuk ke Pimpinan.</p></div>
      <section class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-5"><input v-model.trim="filters.q" type="search" placeholder="Cari tiket, judul, nama, NIM" class="rounded-xl border border-slate-200 px-3 py-2.5 text-xs lg:col-span-2" /><select v-model="filters.status" class="rounded-xl border border-slate-200 px-3 py-2.5 text-xs"><option value="">Semua status</option><option v-for="status in statuses" :key="status" :value="status">{{ status }}</option></select><select v-model="filters.kategori_id" class="rounded-xl border border-slate-200 px-3 py-2.5 text-xs"><option value="">Semua kategori</option><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.nama }}</option></select><select v-model="filters.unit_id" class="rounded-xl border border-slate-200 px-3 py-2.5 text-xs"><option value="">Semua unit</option><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.nama_unit }}</option></select><label class="text-[11px] text-slate-500">Dari<input v-model="filters.from" type="date" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-xs text-slate-800" /></label><label class="text-[11px] text-slate-500">Sampai<input v-model="filters.to" type="date" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2 text-xs text-slate-800" /></label><button type="button" class="rounded-xl bg-blue-950 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-50" :disabled="loading" @click="load">{{ loading ? 'Memuat...' : 'Terapkan Filter' }}</button></section>
      <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 p-4 text-xs text-red-700">{{ error }} <button type="button" class="ml-2 font-semibold underline" @click="load">Coba lagi</button></div>
      <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[1100px] w-full text-left text-xs"><thead class="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr><th class="px-4 py-3">Nomor Tiket</th><th class="px-4 py-3">Masuk Pimpinan</th><th class="px-4 py-3">Judul</th><th class="px-4 py-3">Mahasiswa</th><th class="px-4 py-3">Kategori</th><th class="px-4 py-3">Unit</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Diperbarui</th><th class="px-4 py-3">Aksi</th></tr></thead><tbody class="divide-y divide-slate-200"><tr v-if="loading"><td colspan="9" class="px-4 py-10 text-center text-slate-500">Memuat riwayat...</td></tr><tr v-else-if="!items.length"><td colspan="9" class="px-4 py-10 text-center text-slate-500">Belum ada pengaduan urgensi tinggi yang pernah masuk ke Pimpinan.</td></tr><tr v-for="item in items" :key="item.id" class="hover:bg-slate-50/70"><td class="px-4 py-3 font-semibold text-blue-950">{{ item.kode_tiket || `ADU-${item.id}` }}</td><td class="px-4 py-3 whitespace-nowrap text-slate-600">{{ dateLabel(item.tanggal_masuk_pimpinan) }}</td><td class="max-w-[220px] px-4 py-3 font-semibold text-slate-900">{{ item.judul }}</td><td class="px-4 py-3"><p class="font-semibold">{{ item.user?.mahasiswa?.nama_lengkap || item.user?.nama_lengkap || '-' }}</p><p class="text-[11px] text-slate-500">{{ item.user?.mahasiswa?.nim || '-' }}</p></td><td class="px-4 py-3">{{ item.kategori?.nama || '-' }}</td><td class="px-4 py-3">{{ item.unit?.nama_unit || item.disposisi?.unit?.nama_unit || '-' }}</td><td class="px-4 py-3"><StatusBadge :label="item.status" /></td><td class="px-4 py-3 whitespace-nowrap text-slate-500">{{ dateLabel(item.updated_at, true) }}</td><td class="px-4 py-3"><router-link :to="{ name: 'PimpinanRiwayatTinggiDetail', params: { id: item.id } }" class="font-semibold text-blue-950 hover:underline">Detail</router-link></td></tr></tbody></table></div></section>
    </section>
  </PimpinanLayout>
</template>
<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import PimpinanLayout from '../../layouts/PimpinanLayout.vue'
import StatusBadge from '../../components/StatusBadge.vue'
import service from '../../services/pimpinan.service'
import { dateLabel, errorMessage } from '../../utils/api'
const items = ref([]); const categories = ref([]); const units = ref([]); const loading = ref(true); const error = ref(''); const statuses = ['Menunggu Disposisi', 'Diteruskan ke Unit', 'Diproses', 'Selesai', 'Ditolak']; const filters = reactive({ q: '', status: '', kategori_id: '', unit_id: '', from: '', to: '' })
async function load() { loading.value = true; error.value = ''; try { const response = await service.history({ ...filters }); items.value = response.data?.data || response.data || [] } catch (err) { error.value = errorMessage(err, 'Riwayat pengaduan tidak dapat dimuat.') } finally { loading.value = false } }
async function loadLookups() { try { const [categoryResponse, unitResponse] = await Promise.all([service.categories(), service.getUnits()]); categories.value = categoryResponse.data?.data || categoryResponse.data || []; units.value = unitResponse.data?.data || unitResponse.data || [] } catch (err) { error.value = errorMessage(err, 'Filter kategori/unit tidak dapat dimuat.') } }
watch(() => [filters.status, filters.kategori_id, filters.unit_id, filters.from, filters.to], load)
onMounted(async () => { await loadLookups(); await load() })
</script>
