<template>
  <AdminSistemLayout><section class="space-y-5"><div><p class="text-[11px] font-semibold uppercase tracking-wider text-blue-950">Konfigurasi Sistem</p><h2 class="mt-1 text-xl font-bold text-slate-950">Status Kategori dan Unit</h2><p class="mt-1 text-xs text-slate-500">Nonaktifkan pilihan baru tanpa menghapus data lama.</p></div><div v-if="error" class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">{{ error }}</div><div class="grid gap-5 lg:grid-cols-2"><section v-for="group in groups" :key="group.key" class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="text-sm font-bold text-slate-950">{{ group.label }}</h3><div v-if="loading" class="mt-4 text-xs text-slate-500">Memuat...</div><div v-else-if="!group.items.length" class="mt-4 rounded-lg border border-dashed border-slate-200 p-5 text-center text-xs text-slate-500">Belum ada data.</div><div v-else class="mt-4 space-y-3"><div v-for="item in group.items" :key="item.id" class="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 text-xs"><span class="font-semibold text-slate-800">{{ item.nama || item.nama_unit }}</span><button type="button" :disabled="savingId === `${group.key}-${item.id}`" :class="item.is_active === false ? 'bg-red-100 text-red-700' : 'bg-emerald-100 text-emerald-700'" class="rounded-full px-3 py-1.5 font-semibold disabled:opacity-50" @click="toggle(group, item)">{{ savingId === `${group.key}-${item.id}` ? 'Menyimpan...' : item.is_active === false ? 'Aktifkan' : 'Nonaktifkan' }}</button></div></div></section></div></section></AdminSistemLayout>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import AdminSistemLayout from '../../layouts/AdminSistemLayout.vue'
import service from '../../services/admin-sistem.service'
import { errorMessage, responseList } from '../../utils/api'
import { useToastStore } from '../../stores/toast'
const categories = ref([]); const units = ref([]); const loading = ref(true); const error = ref(''); const savingId = ref(''); const toast = useToastStore()
const groups = computed(() => [{ key: 'categories', label: 'Kategori', items: categories.value }, { key: 'units', label: 'Unit', items: units.value }])
async function load() { loading.value = true; try { const [categoryResponse, unitResponse] = await Promise.all([service.categories(), service.units()]); categories.value = responseList(categoryResponse); units.value = responseList(unitResponse) } catch (err) { error.value = errorMessage(err, 'Status konfigurasi tidak dapat dimuat.') } finally { loading.value = false } }
async function toggle(group, item) { const next = item.is_active === false; if (!window.confirm(`${next ? 'Aktifkan' : 'Nonaktifkan'} ${item.nama || item.nama_unit}?`)) return; savingId.value = `${group.key}-${item.id}`; try { if (group.key === 'categories') await service.setCategoryStatus(item.id, { is_active: next }); else await service.setUnitStatus(item.id, { is_active: next }); item.is_active = next; toast.add({ type: 'success', message: 'Status berhasil diperbarui.' }) } catch (err) { toast.add({ type: 'danger', message: errorMessage(err, 'Status gagal diperbarui.') }) } finally { savingId.value = '' } }
onMounted(load)
</script>
